import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import "./themes.css";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          <ThemeWrapper>
            {children}
            <ThemeSwitcher />
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
